package adsen.exec.imports;

/**
 * These are the types of files and their endings that will be supported by Helium
 */
public enum FileType {
    /**
     * Standard Helium code, can be executed, and can
     */
    STANDARD("he"),
    /**
     * Same as a {@link FileType#STANDARD} code file, but can't contain a main function. Used to store library functions
     */
    LIBRARY("libhe"),
    /**
     * This will be the extension used by translated files generated by the {@link adsen.exec.translator.Translator}
     */
    TRANSLATED(""),
    ;

    public final String ending;

    FileType(String ending) {
        this.ending = ending;
    }
}
